In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [7]:
df = pd.read_csv('Churn_Modelling.csv')

In [8]:
df.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          225       NaN  Female  41.0   
2          3    15619304      Onio          629    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850     Spain  Female  43.0   
5          6    15574012       Chu          645     Spain    Male  44.0   
6          7    15592531  Bartlett          619    France    Male  50.0   
7          8    15656148    Obinna          376   Germany     NaN   NaN   
8          9    15792365        He          501    France    Male  44.0   
9         10    15592389        H?          684    France    Male  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [9]:
#Checking the Null Values

df.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender              True
Age                 True
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [10]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          1
Gender             1
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [11]:
# How to Remove the Row, the only row has a null value

In [12]:
#dataset.[dataset["Geography"].isnull()].index.tolist()

In [13]:
#Fill with a own Value

df.fillna("abc")

RowNumber  CustomerId    Surname  CreditScore Geography  Gender Age  \
0             1    15634602   Hargrave          619    France  Female  42   
1             2    15647311       Hill          225       abc  Female  41   
2             3    15619304       Onio          629    France  Female  42   
3             4    15701354       Boni          699    France  Female  39   
4             5    15737888   Mitchell          850     Spain  Female  43   
...         ...         ...        ...          ...       ...     ...  ..   
9995       9996    15606229   Obijiaku          771    France    Male  39   
9996       9997    15569892  Johnstone          516    France    Male  35   
9997       9998    15584532        Liu          709    France  Female  36   
9998       9999    15682355  Sabbatini          772   Germany    Male  42   
9999      10000    15628319     Walker          792    France  Female  28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [14]:
df["Geography"].fillna(df["Geography"].mode()[0], inplace = True)

In [15]:
df["Gender"].fillna(df["Gender"].mode()[0], inplace = True)

In [16]:
df["Age"].fillna(df["Age"].mean(), inplace = True)

In [17]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
0             1    15634602   Hargrave          619    France  Female  42.0   
1             2    15647311       Hill          225    France  Female  41.0   
2             3    15619304       Onio          629    France  Female  42.0   
3             4    15701354       Boni          699    France  Female  39.0   
4             5    15737888   Mitchell          850     Spain  Female  43.0   
...         ...         ...        ...          ...       ...     ...   ...   
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [18]:
df.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

# Split the data for Input and OutPut

In [19]:
#explicitly mentio the each row
#x = df.iloc[:, [2, 3, 4, 5]] # 2, 3, 4, 5 are the only rows if we want

x = df.iloc[:, 3:13]
y = df.iloc[:, 13]

In [20]:
type(x)

pandas.core.frame.DataFrame

In [21]:
# we need to convert into arrays, then only we can able to 
# apply to the machine learning models, we can only visualise the 
# pandas dataframe, we can't predict

x = df.iloc[:, 3:13].values
y = df.iloc[:, 13].values

In [22]:
type(x)

numpy.ndarray

# Handling the categorical data

In [23]:
df["Geography"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [24]:
df["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [25]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [26]:
x[0]

array([619, 'France', 'Female', 42.0, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [42]:
ct = ColumnTransformer([("oh", OneHotEncoder(),[1, 2])], remainder = "passthrough")
x = ct.fit_transform(x)

In [28]:
x[0]

array([619, 'France', 'Female', 42.0, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [29]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [30]:
x.shape

(10000, 10)

# Split the Data for Training and Testing

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [33]:
x_train.shape

(8000, 10)

In [34]:
y_train.shape

(8000,)

In [35]:
x_test.shape

(2000, 10)

In [36]:
y_test.shape

(2000,)

In [37]:
# Random State ?
# if we used random state = 0 , then the rows will not be changed
# if we not using "randomState" the  the data get shuffeled

# Feature Scaling

In [38]:
from sklearn.preprocessing import StandardScaler

In [39]:
sc = StandardScaler()

In [40]:
x_train = sc.fit_transform(x_train)

ValueError: could not convert string to float: 'Spain'

In [41]:
x_train

array([[667, 'Spain', 'Female', ..., 1, 0, 163830.64],
       [427, 'Germany', 'Male', ..., 1, 1, 57098.0],
       [535, 'France', 'Female', ..., 1, 0, 185630.76],
       ...,
       [738, 'France', 'Male', ..., 1, 0, 181429.87],
       [590, 'Spain', 'Female', ..., 1, 1, 148750.16],
       [623, 'Germany', 'Female', ..., 1, 0, 118855.26]], dtype=object)

# Model Building