# NUMPY

In [ ]:
import numpy as np

In [2]:
list = [1, 2, 3, 4, 5]

In [3]:
a = np.array(list)

In [4]:
type(a)

numpy.ndarray

In [5]:
from numpy import * # Import all classes in the Module

In [12]:
print(a) # Basically its a Column Matrix

[1 2 3 4 5]


In [10]:
np.shape(a) # or a.shape

(5,)

In [13]:
a.ndim

1

In [14]:
a.size

5

In [18]:
min(a)

1

In [19]:
max(a)

5

In [20]:
listTwo = ["raja", "rahul", 1, 2, 3, 3.4]

In [21]:
np.array(listTwo)

array(['raja', 'rahul', '1', '2', '3', '3.4'], dtype='<U5')

In [22]:
type(listTwo)

list

In [23]:
randomNum = np.array(listTwo)

In [24]:
type(randomNum)

numpy.ndarray

In [25]:
# numpy arrays are muttable

In [26]:
# Creating a 2D Array

twoDarray = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [27]:
twoDarray

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [28]:
type(twoDarray)

list

In [29]:
numpytwoDarray = np.array(twoDarray)

In [30]:
numpytwoDarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
type(numpytwoDarray)

numpy.ndarray

In [32]:
numpytwoDarray.shape

(4, 3)

In [33]:
#Checking the number of dimension

numpytwoDarray.ndim

2

In [35]:
# Accessing the unique column in each row 

numpytwoDarray[:,1]

array([ 2,  5,  8, 11])

# TASK 01

In [43]:
taskArray = [["Raju", 19, 30000, "Software Engineer"], ["Anu", 21, 32000, "Web Developer"], ["Kotis", 23, 34000, "Marketting Manager"], ["Kesavan", 21, 40000, "Software Engineer"]]
print(taskArray)
temp = np.array(taskArray)
print(type(temp))
temp

[['Raju', 19, 30000, 'Software Engineer'], ['Anu', 21, 32000, 'Web Developer'], ['Kotis', 23, 34000, 'Marketting Manager'], ['Kesavan', 21, 40000, 'Software Engineer']]
<class 'numpy.ndarray'>


array([['Raju', '19', '30000', 'Software Engineer'],
       ['Anu', '21', '32000', 'Web Developer'],
       ['Kotis', '23', '34000', 'Marketting Manager'],
       ['Kesavan', '21', '40000', 'Software Engineer']], dtype='<U18')

# Functions in Numpy

1.  Ones
2.  Zeros
3.  Eye
4.  Arrange
5.  random.randint
6.  random.rand
7.  linspace
8.  reshape
9.  concatenate
10. delete
11. ravel
12. flaten


In [44]:
# Creates a Single 1D Array with one element with respective specified number

np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(10, 25)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
np.linspace(1, 2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [50]:
np.linspace(1, 2, 230)

array([1.        , 1.00436681, 1.00873362, 1.01310044, 1.01746725,
       1.02183406, 1.02620087, 1.03056769, 1.0349345 , 1.03930131,
       1.04366812, 1.04803493, 1.05240175, 1.05676856, 1.06113537,
       1.06550218, 1.069869  , 1.07423581, 1.07860262, 1.08296943,
       1.08733624, 1.09170306, 1.09606987, 1.10043668, 1.10480349,
       1.10917031, 1.11353712, 1.11790393, 1.12227074, 1.12663755,
       1.13100437, 1.13537118, 1.13973799, 1.1441048 , 1.14847162,
       1.15283843, 1.15720524, 1.16157205, 1.16593886, 1.17030568,
       1.17467249, 1.1790393 , 1.18340611, 1.18777293, 1.19213974,
       1.19650655, 1.20087336, 1.20524017, 1.20960699, 1.2139738 ,
       1.21834061, 1.22270742, 1.22707424, 1.23144105, 1.23580786,
       1.24017467, 1.24454148, 1.2489083 , 1.25327511, 1.25764192,
       1.26200873, 1.26637555, 1.27074236, 1.27510917, 1.27947598,
       1.28384279, 1.28820961, 1.29257642, 1.29694323, 1.30131004,
       1.30567686, 1.31004367, 1.31441048, 1.31877729, 1.32314

In [99]:
np.random.randint(20)

2

# TASK 02

In [ ]:
# Create an array with arrange consist of 16 elements ranging
# Create an linspace array with elements ranging between 4,5

In [101]:
oneArray = np.arange(16)
oneArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [103]:
twoArray = np.linspace(4,5,20)
twoArray

array([4.        , 4.05263158, 4.10526316, 4.15789474, 4.21052632,
       4.26315789, 4.31578947, 4.36842105, 4.42105263, 4.47368421,
       4.52631579, 4.57894737, 4.63157895, 4.68421053, 4.73684211,
       4.78947368, 4.84210526, 4.89473684, 4.94736842, 5.        ])

In [104]:
threeArray = np.random.randint(9,95,9)
threeArray

array([85, 15, 14, 48, 49, 50, 69, 79, 93])

In [107]:
oneArray.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
twoArray.reshape(4,5)

array([[4.        , 4.05263158, 4.10526316, 4.15789474, 4.21052632],
       [4.26315789, 4.31578947, 4.36842105, 4.42105263, 4.47368421],
       [4.52631579, 4.57894737, 4.63157895, 4.68421053, 4.73684211],
       [4.78947368, 4.84210526, 4.89473684, 4.94736842, 5.        ]])

In [112]:
threeArray.reshape(3,3)

array([[85, 15, 14],
       [48, 49, 50],
       [69, 79, 93]])

In [115]:
# CONCATENATION

d = np.concatenate((oneArray, twoArray), axis = 0)

In [116]:
d

array([ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
        5.        ,  6.        ,  7.        ,  8.        ,  9.        ,
       10.        , 11.        , 12.        , 13.        , 14.        ,
       15.        ,  4.        ,  4.05263158,  4.10526316,  4.15789474,
        4.21052632,  4.26315789,  4.31578947,  4.36842105,  4.42105263,
        4.47368421,  4.52631579,  4.57894737,  4.63157895,  4.68421053,
        4.73684211,  4.78947368,  4.84210526,  4.89473684,  4.94736842,
        5.        ])

In [122]:
d.size

36

In [120]:
e = np.delete(d, [1,2], axis = 0)

In [123]:
e.size

34

In [121]:
e

array([ 0.        ,  3.        ,  4.        ,  5.        ,  6.        ,
        7.        ,  8.        ,  9.        , 10.        , 11.        ,
       12.        , 13.        , 14.        , 15.        ,  4.        ,
        4.05263158,  4.10526316,  4.15789474,  4.21052632,  4.26315789,
        4.31578947,  4.36842105,  4.42105263,  4.47368421,  4.52631579,
        4.57894737,  4.63157895,  4.68421053,  4.73684211,  4.78947368,
        4.84210526,  4.89473684,  4.94736842,  5.        ])